name = "a0b_stm32f0_generic_usart"
description = "A0B: STM32F0+ USART Generic Driver"
version = "0.1.0-dev"

authors = ["Vadim Godunko"]
maintainers = ["Vadim Godunko <vgodunko@gmail.com>"]
maintainers-logins = ["godunko"]
licenses = "Apache-2.0 WITH LLVM-exception"
tags = ["a0b", "embedded", "usart", "uart", "stm32"]

project-files = ["gnat/a0b_stm32f0_generic_usart.gpr"]

[configuration]
generate_ada = false
generate_c = false
generate_gpr = true

[[depends-on]]
a0b_callbacks = "*"
